/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author allan
 */
public class ViewPrincipalVenda extends javax.swing.JFrame {

    /**
     * Creates new form ViewPrincipalVenda
     */
    public ViewPrincipalVenda() {
        setLocationRelativeTo(this);        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnPDV = new javax.swing.JMenuItem();
        mnRelatorioVendas = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\allan\\Downloads\\ponto-de-venda (1).png")); // NOI18N

        jMenu1.setText("Venda");

        mnPDV.setText("PDV");
        mnPDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPDVActionPerformed(evt);
            }
        });
        jMenu1.add(mnPDV);

        jMenuBar1.add(jMenu1);

        mnRelatorioVendas.setText("Relatórios");
        mnRelatorioVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRelatorioVendasActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Relatório de Vendas");
        mnRelatorioVendas.add(jMenuItem2);

        jMenuBar1.add(mnRelatorioVendas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnPDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPDVActionPerformed
        ViewPDV cadVenda = new ViewPDV();
        cadVenda.setLocationRelativeTo(this);
        cadVenda.setVisible(true);
    }//GEN-LAST:event_mnPDVActionPerformed

    private void mnRelatorioVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRelatorioVendasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnRelatorioVendasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem mnPDV;
    private javax.swing.JMenu mnRelatorioVendas;
    // End of variables declaration//GEN-END:variables
}
